CREATE TABLE `base_login_account_auth` (
  `sid` bigint(16) unsigned NOT NULL AUTO_INCREMENT,
  `user_account_sid` bigint(16) DEFAULT NULL COMMENT '用户uid',
  `login_id` varchar(50) NOT NULL  COMMENT '登录账户',
  `password` varchar(64) DEFAULT NULL COMMENT '密码',
  `login_type` smallint(2) DEFAULT NULL COMMENT '账户登录类型：1-自定义账号+密码；2-手机号+密码；3-手机号+验证码；4-邮箱密码；5-二维码；6-微信openId；',
  `login_status` smallint(2) DEFAULT NULL COMMENT '账户状态（暂时没用）',
  `del_flag` smallint(2) NOT NULL COMMENT '删除标志\r\n            0 - 正常\r\n            1 - 删除',
  `version` int(10) NOT NULL COMMENT '版本号',
  `created_by` varchar(50) NOT NULL COMMENT '创建人\r\n            登录帐号',
  `create_date` datetime NOT NULL,
  `update_by` varchar(50) DEFAULT NULL COMMENT '修改人\r\n            登录的帐号',
  `update_date` datetime DEFAULT NULL COMMENT '修改时间',
  `create_by` varchar(255) DEFAULT NULL,
  `version` int(10) NOT NULL COMMENT '版本号',
  `current_version` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`sid`),
  KEY `idx_user_account_sid` (`user_account_sid`),
  KEY `idx_login_id` (`login_id`)
) ENGINE=InnoDB AUTO_INCREMENT=356716 DEFAULT CHARSET=utf8 COMMENT='用户登录鉴权表';
CREATE TABLE `base_user_account` (
  `sid` bigint(16) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` varchar(32) NOT NULL COMMENT '用户账号ID，业务主键，默认生成规则：UUID',
  `account_status` smallint(2) NOT NULL COMMENT '账户状态（暂时没用）',
  `secret_key` varchar(32) DEFAULT NULL,
  `account_type` smallint(2) DEFAULT '0' COMMENT '账号类型 0普通账号 1-访客账号',
  `del_flag` smallint(2) NOT NULL COMMENT '删除标志 0 - 正常 1 - 删除',
  `version` int(10) NOT NULL COMMENT '版本号',
  `created_by` varchar(50) NOT NULL COMMENT '创建人\r\n            登录帐号',
  `create_date` datetime NOT NULL,
  `update_by` varchar(50) DEFAULT NULL COMMENT '修改人\r\n            登录的帐号',
  `update_date` datetime DEFAULT NULL COMMENT '修改时间',
  `create_by` varchar(255) DEFAULT NULL,
  `current_version` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`sid`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_project_id_create_date` (`project_id`,`create_date`),
  KEY `idx_project_id` (`project_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1060091 DEFAULT CHARSET=utf8 COMMENT='用户表';